# Generated by Django 3.2.6 on 2021-08-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postdrfapp', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_type',
            new_name='posttype',
        ),
    ]
